// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppFooter: typeof import('./../components/app-footer.vue')['default']
    Header: typeof import('./../components/header.vue')['default']
    Posts: typeof import('./../components/posts.vue')['default']
    PostsItem: typeof import('./../components/posts-item.vue')['default']
    Project: typeof import('./../components/project.vue')['default']
    ProjectsItem: typeof import('./../components/projects-item.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Socials: typeof import('./../components/socials.vue')['default']
    SocialsItem: typeof import('./../components/socials-item.vue')['default']
  }
}
